experiment_name: "personalized-shopping-adk-eval"
run_name_prefix: "eval-run-38" # Increment for a clean run

agent_adapter_class: "agent_eval_framework.adapters.adk_adapter.ADKAgentAdapter"

agent_config:
  agent_module: "personalized_shopping.agent"
  agent_name: "root_agent"

dataset_path: "data/simple.test.jsonl"

column_mapping:
  query: "prompt"
  reference_answer: "reference"
  trajectory: "reference_trajectory" # Ground truth tool calls

metrics:
  # Agent Trajectory Metrics (as strings)
  - "trajectory_exact_match"
  # - "trajectory_in_order_match"
  # - "trajectory_any_order_match"
  # - "trajectory_precision"
  # - "trajectory_recall"

  # Standard Computation Metrics for Final Response
  - "exact_match"
  - "bleu"
  - "rouge_l_sum"
