# agent-eval-framework/config/adk_eval_config.yaml
agent_adapter_class: "agent_eval_framework.adapters.adk_adapter.ADKAgentAdapter"

agent_config:
  agent_module: "personalized_shopping.agent"
  agent_name: "root_agent"

dataset_path: "../eval/eval_data/simple.test.jsonl" # Path relative to agent-eval-framework root

column_mapping:
  prompt: "query"
  reference: "reference_answer"

metrics:
  - name: "exact_match"
    type: "computation"
  - name: "bleu"
    type: "computation"
  - name: "rouge_l_sum"
    type: "computation"
  # Example LLM-based metric from Vertex AI
  # - name: "fluency"
  #   type: "pointwise"
  # Example custom metric (requires function in python path)
  # - name: "my_tool_use_metric"
  #   type: "custom_function"
  #   custom_function_path: "my_metrics.tool_check.calculate_tool_accuracy"

experiment_name: "personalized-shopping-adk-eval"
