experiment_name: "personalized-shopping-adk-eval"
run_name_prefix: "eval-run-32" # Increment for a clean run

agent_adapter_class: "agent_eval_framework.adapters.adk_adapter.ADKAgentAdapter"

agent_config:
  agent_module: "personalized_shopping.agent"
  agent_name: "root_agent"

dataset_path: "data/simple.test.jsonl"

column_mapping:
  # Maps a column in your DataFrame to the 'response' expected by some metrics
  response: "response"
  # Maps a column in your DataFrame to the 'reference' expected by some metrics
  reference: "reference"
  # CRITICAL for SERVER-SIDE trajectory metrics:
  # DataFrame column containing the agent's actual tool calls
  prediction: "predicted_trajectory"
  # DataFrame column containing the ground truth tool calls
  ground_truth: "reference_trajectory"

metrics:
  # Vertex AI Server-Side Trajectory Metrics
  - name: trajectory_exact_match
  # - name: trajectory_precision
  # - name: trajectory_recall

  # Standard Computation Metrics (Server-Side)
  - name: exact_match
    type: computation
  - name: bleu
    type: computation
  - name: rouge_l_sum
    type: computation
